
accent_color: rgb(147,190,37)
title: Lunar Codebase
email: sabinowitz@gmail.com
tagline: "Software in orbit"

remote_theme: hydecorp/hydejack@v9.1.2
gems:
  - jekyll-include-cache

  plugins:
  - jekyll-include-cache