
accent_color: rgb(147,190,37)
title: Lunar Codebase
tagline: "Software in orbit"
email: sabinowitz@gmail.com


remote_theme: hydecorp/hydejack@v9.1.2


accent_image: /assets/img/bettercrop.jpg

hydejack:
   no_navbar:           true

plugins:
  - jekyll-include-cache