
accent_color: rgb(147,190,37)
title: Lunar Codebase
tagline: BANG ZOOM
email: sabinowitz@gmail.com


remote_theme: hydecorp/hydejack@v9.1.2

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          EB+Garamond:700|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          EB Garamond, Helvetica, Arial, sans-serif


accent_image: /assets/img/bettercrop.jpg

hydejack:
   no_navbar:           true

plugins:
  - jekyll-include-cache