
accent_color: rgb(147,190,37)
title: Lunar Codebase
email: sabinowitz@gmail.com
tagline: "Software in orbit"

remote_theme: hydecorp/hydejack@v9.1.2


accent_image: /assets/img/earthriseCrop.jpg

plugins:
  - jekyll-include-cache